site_name: Systemy Wspomagania Pracy Zespołowej
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs
    - header.autohide
  palette:
    primary: 'indigo'
    accent: 'amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/logo.svg'
  favicon: 'assets/favicon.ico'

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Strona główna: index.md
  - Projekt:
      - Temat: projekt/temat.md
      - Autorzy: projekt/autorzy.md
  - Teoria:
      - Podstawy: teoria/podstawy.md
      - Narzędzia: teoria/narzedzia.md
  - Praktyka:
      - Instrukcje: praktyka/instrukcje.md
      - Przykłady: przyklady.md
  - Bezpieczeństwo: polityka_bezpieczenstwa.md
  - Dokumentacja: dokumentacja.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
