site_name: Polish Volleyball Hub
site_url: https://your-site-url.com
nav:
  - Home: index.md
  - About Me: about.md
  - Plus Liga Teams: teams.md
  - National Team of Poland: nationalTeam.md
  - Authors: authors.md

theme:
  name: material
  palette:
    scheme: default
    primary: red
    accent: white
  font:
    text: "Roboto"
    code: "JetBrains Mono"

extra_css:
  - styles/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - toc:
      permalink: true
